version: "3.9"
services:

  # postgres
  xquery-pg:
    image: postgres:13
    container_name: "${PROJECT_NAME}-pg"
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}




